services:
  - type: web
    name: kritika-telegram-bot
    runtime: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7988273088:AAGhxSxjCK0H1qg51tEaf4WviU9hSF1dmfc
      - key: ADMIN_ID
        value: "6138277581"
      - key: GEMINI_API_KEY
        value: AIzaSyDc6wrTkV2k4AWl72NZxET6URrXCbM8haM
